import type { EmployeeRequest, Vehicle } from '../types';

const testCaseData = {
  employees: [
    {
      employee_id: 'E01',
      pickup_lat: 12.936,
      pickup_lng: 77.624,
      drop_lat: 12.9716,
      drop_lng: 77.5946,
      priority: 1,
      earliest_pickup: '08:10:00',
      latest_drop: '08:45:00',
      vehicle_preference: 'premium',
      sharing_preference: 'single' as const,
    },
    {
      employee_id: 'E02',
      pickup_lat: 12.938,
      pickup_lng: 77.626,
      drop_lat: 12.9716,
      drop_lng: 77.5946,
      priority: 1,
      earliest_pickup: '08:15:00',
      latest_drop: '08:50:00',
      vehicle_preference: 'premium',
      sharing_preference: 'single' as const,
    },
    {
      employee_id: 'E03',
      pickup_lat: 12.94,
      pickup_lng: 77.628,
      drop_lat: 12.9716,
      drop_lng: 77.5946,
      priority: 1,
      earliest_pickup: '08:20:00',
      latest_drop: '08:55:00',
      vehicle_preference: 'premium',
      sharing_preference: 'single' as const,
    },
    {
      employee_id: 'E04',
      pickup_lat: 12.942,
      pickup_lng: 77.63,
      drop_lat: 12.9716,
      drop_lng: 77.5946,
      priority: 1,
      earliest_pickup: '08:25:00',
      latest_drop: '09:00:00',
      vehicle_preference: 'premium',
      sharing_preference: 'single' as const,
    },
    {
      employee_id: 'E05',
      pickup_lat: 12.93,
      pickup_lng: 77.62,
      drop_lat: 12.9716,
      drop_lng: 77.5946,
      priority: 2,
      earliest_pickup: '08:30:00',
      latest_drop: '09:30:00',
      vehicle_preference: 'any',
      sharing_preference: 'double' as const,
    },
    {
      employee_id: 'E06',
      pickup_lat: 12.928,
      pickup_lng: 77.618,
      drop_lat: 12.9716,
      drop_lng: 77.5946,
      priority: 2,
      earliest_pickup: '08:30:00',
      latest_drop: '09:30:00',
      vehicle_preference: 'any',
      sharing_preference: 'double' as const,
    },
    {
      employee_id: 'E07',
      pickup_lat: 12.95,
      pickup_lng: 77.635,
      drop_lat: 12.9716,
      drop_lng: 77.5946,
      priority: 3,
      earliest_pickup: '08:45:00',
      latest_drop: '10:00:00',
      vehicle_preference: 'normal',
      sharing_preference: 'triple' as const,
    },
    {
      employee_id: 'E08',
      pickup_lat: 12.948,
      pickup_lng: 77.633,
      drop_lat: 12.9716,
      drop_lng: 77.5946,
      priority: 3,
      earliest_pickup: '08:45:00',
      latest_drop: '10:00:00',
      vehicle_preference: 'normal',
      sharing_preference: 'triple' as const,
    },
    {
      employee_id: 'E09',
      pickup_lat: 12.915,
      pickup_lng: 77.605,
      drop_lat: 12.9716,
      drop_lng: 77.5946,
      priority: 4,
      earliest_pickup: '09:30:00',
      latest_drop: '11:00:00',
      vehicle_preference: 'any',
      sharing_preference: 'triple' as const,
    },
    {
      employee_id: 'E10',
      pickup_lat: 13.05,
      pickup_lng: 77.8,
      drop_lat: 12.9716,
      drop_lng: 77.5946,
      priority: 1,
      earliest_pickup: '08:00:00',
      latest_drop: '08:40:00',
      vehicle_preference: 'premium',
      sharing_preference: 'single' as const,
    },
  ],
  vehicles: [
    {
      vehicle_id: 'V01',
      current_lat: 12.935,
      current_lng: 77.62,
      capacity: 2,
      cost_per_km: 10.0,
      avg_speed_kmph: 30.0,
      available_from: '08:00:00',
      category: 'premium',
    },
    {
      vehicle_id: 'V02',
      current_lat: 12.94,
      current_lng: 77.625,
      capacity: 2,
      cost_per_km: 11.0,
      avg_speed_kmph: 28.0,
      available_from: '08:00:00',
      category: 'premium',
    },
    {
      vehicle_id: 'V03',
      current_lat: 12.92,
      current_lng: 77.61,
      capacity: 4,
      cost_per_km: 14.0,
      avg_speed_kmph: 35.0,
      available_from: '08:00:00',
      category: 'normal',
    },
    {
      vehicle_id: 'V04',
      current_lat: 12.95,
      current_lng: 77.63,
      capacity: 6,
      cost_per_km: 18.0,
      avg_speed_kmph: 32.0,
      available_from: '08:00:00',
      category: 'normal',
    },
  ],
  baseline: {
    E01: 420.0,
    E02: 425.0,
    E03: 430.0,
    E04: 435.0,
    E05: 400.0,
    E06: 395.0,
    E07: 380.0,
    E08: 385.0,
    E09: 450.0,
    E10: 700.0,
  },
};

export function createTestCaseScenario(scenarioId: string): {
  employees: Omit<EmployeeRequest, 'id'>[];
  vehicles: Omit<Vehicle, 'id'>[];
  baselineCost: number;
} {
  const employees: Omit<EmployeeRequest, 'id'>[] = testCaseData.employees.map((emp) => ({
    scenario_id: scenarioId,
    employee_id: emp.employee_id,
    priority: emp.priority === 1 ? 'high' : emp.priority === 2 ? 'medium' : 'low',
    pickup_lat: emp.pickup_lat,
    pickup_lng: emp.pickup_lng,
    pickup_address: `Location - ${emp.employee_id}`,
    destination_lat: emp.drop_lat,
    destination_lng: emp.drop_lng,
    destination_address: 'Office (Drop-off)',
    time_window_start: emp.earliest_pickup,
    time_window_end: emp.latest_drop,
    vehicle_preference: emp.vehicle_preference === 'premium' ? 'premium' : 'normal',
    sharing_preference: emp.sharing_preference,
  }));

  const vehicles: Omit<Vehicle, 'id'>[] = testCaseData.vehicles.map((veh) => ({
    scenario_id: scenarioId,
    vehicle_id: veh.vehicle_id,
    fuel_type: 'petrol',
    vehicle_mode: veh.category === 'premium' ? '4-wheeler' : veh.capacity >= 6 ? 'van' : '4-wheeler',
    capacity: veh.capacity,
    cost_per_km: veh.cost_per_km,
    avg_mileage: 15.0,
    avg_speed: veh.avg_speed_kmph,
    vehicle_age: 2.0,
    current_lat: veh.current_lat,
    current_lng: veh.current_lng,
    current_address: `Vehicle Location - ${veh.vehicle_id}`,
    availability_time: veh.available_from,
  }));

  const baselineCost = Object.values(testCaseData.baseline).reduce((a, b) => a + b, 0);

  return { employees, vehicles, baselineCost };
}
